### ISSUE TITLE
Create Makefile to build bagit lambda

### ISSUE THREAD

**Issue by coverbeck** [DataBiosphere/bagit-firecloud-lambda#2]
Need a makefile and/or instructions on how to build/deploy.

┆Epic: bagit-firecloud lambda handoff
┆Issue Number: BFL-1

**Comment by mjkrause** [comment]
I work on this as it relates to the ability of standing up pre-dev instances of that lambda so we can test deploying new code to a test instance first before deploying to the dev instance.
