### ISSUE TITLE
Provide sample .tsv files pushed to FireCloud

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/bagit-firecloud-lambda#5]
Provide sample/example .tsv files to the Broad that include DOS URLs, in preparation for our March demo. These can be actual files created by the `bagit_to_firecloud` Lambda, or hand-crafted files. In either case, this should be done soon, preferably by EOD 3/22.

**Comment by coverbeck** [comment]
Shared my FC workspace with data exported from FC with FC folks.
