### ISSUE TITLE
Retry failed HTTP requests when exporting to FireCloud

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/bagit-firecloud-lambda#9]
Currently when exporting to FireCloud the HTTP requests are only tried once, and if it fails, the export fails.
There are many cases in an HTTP request can fail and a subsequent retry will succeed, and to have a reliable/robust system, retry is essential.

There are a variety of ways to implement retrying operations.
It looks like the requests package does provide retry support, so that may be a good option.
Another option to consider is the @retry decorated developed by the HCA data-store team, here: https://github.com/HumanCellAtlas/data-store/blob/master/dss/util/retry.py

**Comment by mjkrause** [comment]
opened PR (#16)
